# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow with schedule
  schedule:
    # Runs at 00:00 UTC every day
    - cron:  '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update-data"
  update-data:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup Python
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      
      # Pip install
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # Runs fetch_problems_all.py
      - name: Run fetch_data.py
        run: python fetch_data.py
      
      # Commit problems_all.json
      - name: Commit problems_all.json
        uses: stefanzweifel/git-auto-commit-action@v4.12.0
        with:
          # Commit message
          commit_message: 'ci: update data.json'
          # File pattern used for `git add`. For example `src/*.js`
          file_pattern: data.json

